[
    { "id": "1", "name": "bell pepper", "category": "vegetables", "image": "/images/product-1.jpg", "price": "120", "discount": "0", "rating": "0", "proddesc":"A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until."},
    { "id": "2", "name": "strawberry", "category": "fruits", "image": "/images/product-2.jpg", "price": "80", "discount": "0", "rating": "","proddesc":"A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until."},
    { "id": "3", "name": "green beans", "category": "vegetables", "image": "/images/product-3.jpg", "price": "100", "discount": "0", "rating": "","proddesc":"A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until."},
    { "id": "4", "name": "purple cabbage", "category": "vegetables", "image": "/images/product-4.jpg", "price": "20", "discount": "0", "rating": "","proddesc":"A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until."},
    { "id": "5", "name": "tomato", "category": "vegetables", "image": "/images/product-5.jpg", "price": "70", "discount": "0", "rating": "","proddesc":"A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until."},
    { "id": "6", "name": "brocolli", "category": "vegetables", "image": "/images/product-6.jpg", "price": "55", "discount": "0", "rating": "","proddesc":"A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until."},
    { "id": "7", "name": "carrots", "category": "vegetables", "image": "/images/product-7.jpg", "price": "40", "discount": "0", "rating": "","proddesc":"A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until."},
    { "id": "8", "name": "fruit juice", "category": "fruits", "image": "/images/product-8.jpg", "price": "30", "discount": "0", "rating": "","proddesc":"A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until."},
    { "id": "9", "name": "onion", "category": "vegetables", "image": "/images/product-9.jpg", "price": "190", "discount": "0", "rating": "","proddesc":"A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until."},
    { "id": "10", "name": "apple", "category": "fruits", "image": "/images/product-10.jpg", "price": "50", "discount": "0", "rating": "","proddesc":"A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until."},
    { "id": "11", "name": "garlic", "category": "vegetables", "image": "/images/product-11.jpg", "price": "60", "discount": "0", "rating": "","proddesc":"A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until."},
    { "id": "12", "name": "chilli", "category": "vegetables", "image": "/images/product-12.jpg", "price": "110", "discount": "0", "rating": "","proddesc":"A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until."}
]